create table contact
(
    id           integer generated by default as identity,
    last_name    varchar(255) not null,
    first_name   varchar(255) not null,
    e_mail       varchar(255) not null,
    phone_number varchar(255),
    company_id   bigint,
    comment      varchar(255),
    status       varchar(255) not null,
    created      timestamp ,
    last_changed timestamp ,

    primary key (id)
);
alter table contact
    add foreign key (company_id) references company;
insert into contact
values (30, 'Doe', 'John', 'aenyaino@gmailco.ml', '+3672987356', 1, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (31, 'Doe', 'Jane', 'aenyaino@gmailco.ml', '+3672987356', 2, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (32, 'Does', 'John', 'aenyaino@gmailco.ml', '+3672987356', 3, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (33, 'Does', 'Jane', 'aenyaino@gmailco.ml', '+3672987356', 1, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (34, 'Doesnt', 'John', 'aenyaino@gmailco.ml', '+3672987356', 2, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (36, 'Doesnt', 'Jane', 'aenyaino@gmailco.ml', '+3672987356', 3, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (35, 'Tho', 'John', 'aenyaino@gmailco.ml', '+3672987356', 1, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (37, 'Tho', 'Jane', 'aenyaino@gmailco.ml', '+3672987356', 2, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (38, 'Doh', 'John', 'aenyaino@gmailco.ml', '+3672987356', 3, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (39, 'Doh', 'Jane', 'aenyaino@gmailco.ml', '+3672987356', 1, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (40, 'Margaret', 'Margaret', 'aenyaino@gmailco.ml', '+3672987356', 2, 'comment1', 'active', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
insert into contact
values (41, 'Not', 'Margaret', 'aenyaino@gmailco.ml', '+3672987356', 1, 'comment1', 'deleted', '2020-11-02 10:29:02.652', '2020-12-02 10:29:02.652');
